### ISSUE TITLE
Sometimes a piece to move is picked for you

### ISSUE THREAD

**Issue by aopell** [FiftyTwo/EdgeLibrary#14]
Sometimes when it is your turn as a NormalPlayer, a piece to move is automatically picked for you. When this happens, it is impossible to pick another piece and also the red line that draws your path does not exist.

Possibly caused by Computer AI picking a move for you? (Probably not)

**Comment by FiftyTwo** [comment]
Happens every move for bottom team (if both players did NOT jump) and only(?) when the two players are normal

**Comment by aopell** [comment]
Workaround available.

**Comment by aopell** [comment]
"Not necessary to un-workaround" - Jaren
