### ISSUE TITLE
[UPDATE: New info] Down/Up and Up/Down jumps don't work

### ISSUE THREAD

**Issue by aopell** [FiftyTwo/EdgeLibrary#17]
Crash is a NullReferenceException on Line 176 in Board.cs where variable "piece" is null

![image](https://cloud.githubusercontent.com/assets/5026980/5989571/89d083d8-a941-11e4-8c0a-c794fb925f46.png)

**Comment by aopell** [comment]
May only happen on double jumps

**Comment by FiftyTwo** [comment]
Does not happen on double jumps

**Comment by aopell** [comment]
Does not seem to happen anymore

**Comment by aopell** [comment]
Happens with NormalPlayers as well.
Counts wrong.
Selects wrong final square.

[Image](http://i.imgur.com/1iYGjyq.png)

**Comment by aopell** [comment]
Due to a bug in the jump code where placeholder pieces are not added. the piece thinks, therefore, that it should jump back over a piece that was already removed.
