### ISSUE TITLE
ComputerPlayer should not run the same 2 moves over and over

### ISSUE THREAD

**Issue by aopell** [FiftyTwo/EdgeLibrary#18]
This should not happen:

http://youtu.be/uGBR5mcT0uU

Simple Fix: (CONCEPT!)

```C#
if(BestMove == MoveFromTwoTurnsAgo)
{
    PickNextBestMove()
}
```

**Comment by FiftyTwo** [comment]
It'll still not be as random as it should be. I'm going to just shuffle all moves with the same 'value' so it doesn't do the same moves over and over again but also doesn't allow itself to be captured

**Comment by FiftyTwo** [comment]
It would probably work, except the generation of SortedMove.PiecesLostNext is not working correctly. I'll probably fix it next week.

**Comment by FiftyTwo** [comment]
There is a good chance this is fixed, but I haven't been able to test it enough to be sure :fireworks: :droplet: :fire: :mount_fuji: :ocean:
