### ISSUE TITLE
Between the third and fourth waypoint, enemies move between the two waypoints

### ISSUE THREAD

**Issue by FiftyTwo** [FiftyTwo/EdgeLibrary#39]
Enemies target two waypoints at once

**Comment by aopell** [comment]
The target destination switches between the third and fourth waypoints every update.

**Comment by FiftyTwo** [comment]
Action is not removed - same action calls Stop() twice in different updates. Could possibly be not removed in time

**Comment by FiftyTwo** [comment]
Workaround available

**Comment by aopell** [comment]
It is fixed now
